version: "3.7"

services:
  ws-nginx:
    image: nginx
    container_name: ws-mock-nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 8080:8080

  ws:
    container_name: ws-mock
    build:
      context: "./"
      dockerfile: Dockerfile
    ports:
      - 8090:8090
